service:
  name: doit-aws-nodejs

provider:
  name: aws
  runtime: nodejs6.10
  timeout: 300
  stage: dev
  region: eu-west-1 # paris

plugins:
  - serverless-webpack

functions:
  doit-node-128:
    handler: handler.run
    memorySize: 128
    events:
      - http:
          path: api/doit/128
          method: get
  doit-node-256:
    handler: handler.run
    memorySize: 256
    events:
      - http:
          path: api/doit/256
          method: get
  doit-node-512:
    handler: handler.run
    memorySize: 512
    events:
      - http:
          path: api/doit/512
          method: get
